### ISSUE TITLE
Зависание НА при вызове сервиса graph_image.create_graph_image

### ISSUE THREAD

**Issue by tudimoncom** [malinovsku/ha-graph-image#1]
После обновления Home Assistant до 2023.5.*, при вызове сервиса получения картинки, перестает работать НА (не работает веб морда, телеграм-бот, автоматизации), потом ребутится походу сторожевой собакой.

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
ha-graph-image  v0.0.5

В журнале похоже описывается так:
May 11 06:19:17 homeassistant kernel: kauditd_printk_skb: 1 callbacks suppressed
May 11 06:19:17 homeassistant kernel: audit: type=1334 audit(1683785957.783:2401): prog-id=1074 op=UNLOAD

**Comment by agamemnen** [comment]
Столкнулся с аналогичной проблемой. Хотелось бы послушать решение.

**Comment by malinovsku** [comment]
проверил разные комбинации вызова и зависание возникает при использовании отправки сразу в notify, просто картинка формируется без ошибок. 
вызов службы notify поправлю, а для подтверждения можете направить как вызываете сервис? с какими параметрами?

**Comment by malinovsku** [comment]
[v0.0.6 исправлено зависание Home Assistant при вызове c параметром notify](https://github.com/malinovsku/ha-graph-image/releases/tag/v0.0.6)

**Comment by tudimoncom** [comment]
```
         - service: graph_image.create_graph_image
           data:
             in_folderfile: /config/tmp/graph_cpu.png
             in_time_start: 12
             in_time_end: 0
             in_name_notify: notify.me_group
             in_caption_notify: CPU statistics 12h
             in_data_notify: {}
             in_size_ticks: 10
             in_linewidth: 1
             in_linesmooth: 1
             in_lineinterp: linear_interp
             in_rate_ticks: false
             in_style: Solarize_Light2
           target:
             entity_id:
               - sensor.cpu_temperature
               - sensor.processor_use
               - sensor.ds18b20
```

**Comment by tudimoncom** [comment]
v0.0.6.
когда включен нотифи, то НА виснет. может просто убрать этот функционал? пусть нотифи отдельно будет вызываться и слать картинку..

**Comment by tudimoncom** [comment]
обновил компонент до v0.0.7, удалил нотифи, но теперь при вызове службы "Unknown error". Вызов вот так делаю:

```
service: graph_image.create_graph_image
data:
  in_folderfile: /config/tmp/graph_cpu.png
  in_time_start: 12
  in_time_end: 0
  in_size_ticks: 10
  in_linewidth: 1
  in_linesmooth: 1
  in_lineinterp: linear_interp
  in_rate_ticks: false
  in_style: classic
target:
  entity_id:
    - sensor.cpu_temperature
    - sensor.processor_use
    - sensor.ds18b20

```
